### ISSUE TITLE
gh-pages

### ISSUE THREAD

**Issue by marekhrabe** [HenrikJoreteg/emoji-images#7]
Can you please create a branch `gh-pages`? That way, people can load images from GitHub CDN like in my fork (http://marekhrabe.github.io/emoji-images/pngs/+1.png)

**Comment by HenrikJoreteg** [comment]
Done. Sorry this has been sitting forever, if you're interested in helping maintain this, let me know: https://github.com/HenrikJoreteg/emoji-images/issues/11
